package de.zbidi.jobtracker.jobapplication;

import java.util.Optional;

import de.zbidi.jobtracker.common.ResourceNotFoundException;
import de.zbidi.jobtracker.company.Company;
import de.zbidi.jobtracker.company.CompanyRepository;
import de.zbidi.jobtracker.recruiter.Recruiter;
import de.zbidi.jobtracker.recruiter.RecruiterRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.util.ReflectionTestUtils;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatExceptionOfType;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.BDDMockito.given;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;

/**
 * Fast unit test: repositories mocked, no Spring, no Docker.
 * {@link JobApplicationServiceIntegrationTest} covers the same rules against real Postgres.
 */
@ExtendWith(MockitoExtension.class)
class JobApplicationServiceTest {

	@Mock
	JobApplicationRepository jobApplicationRepository;

	@Mock
	CompanyRepository companyRepository;

	@Mock
	RecruiterRepository recruiterRepository;

	@InjectMocks
	JobApplicationService service;

	private final Company acme = withId(new Company("ACME GmbH", "Berlin", null), 1L);

	// --- PATCH status ---

	@Test
	void changeStatusFromRejectedToInterviewThrowsAndDoesNotSave() {
		JobApplication rejected = application(Status.APPLIED, Status.REJECTED);
		given(jobApplicationRepository.findById(5L)).willReturn(Optional.of(rejected));

		assertThatExceptionOfType(InvalidStatusTransitionException.class)
				.isThrownBy(() -> service.changeStatus(5L, Status.INTERVIEW))
				.satisfies(e -> {
					assertThat(e.getCurrentStatus()).isEqualTo(Status.REJECTED);
					assertThat(e.getRequestedStatus()).isEqualTo(Status.INTERVIEW);
				});
		assertThat(rejected.getStatus()).isEqualTo(Status.REJECTED);
		verify(jobApplicationRepository, never()).saveAndFlush(any());
	}

	@Test
	void changeStatusSavesAndReturnsResponse() {
		JobApplication saved = application();
		given(jobApplicationRepository.findById(5L)).willReturn(Optional.of(saved));
		given(jobApplicationRepository.saveAndFlush(saved)).willReturn(saved);

		JobApplicationResponse response = service.changeStatus(5L, Status.APPLIED);

		assertThat(response.status()).isEqualTo(Status.APPLIED);
		assertThat(response.companyName()).isEqualTo("ACME GmbH");
	}

	@Test
	void changeStatusOnUnknownIdThrowsNotFound() {
		given(jobApplicationRepository.findById(99L)).willReturn(Optional.empty());

		assertThatExceptionOfType(ResourceNotFoundException.class)
				.isThrownBy(() -> service.changeStatus(99L, Status.APPLIED))
				.withMessage("Job application 99 not found");
	}

	@Test
	void changeStatusBlockedWhileRecruiterHasAnotherActiveApplication() {
		Recruiter anna = withId(new Recruiter("Anna Schmidt", "anna@acme.example", acme), 7L);
		JobApplication application = withId(new JobApplication(acme, anna, "Kotlin Developer", null), 5L);
		given(jobApplicationRepository.findById(5L)).willReturn(Optional.of(application));
		given(jobApplicationRepository.existsByRecruiterIdAndStatusInAndIdNot(eq(7L), eq(Status.ACTIVE), eq(5L)))
				.willReturn(true);

		assertThatExceptionOfType(RecruiterConflictException.class)
				.isThrownBy(() -> service.changeStatus(5L, Status.APPLIED))
				.withMessageContaining("Anna Schmidt");
		verify(jobApplicationRepository, never()).saveAndFlush(any());
	}

	// --- POST / GET ---

	@Test
	void createWithUnknownCompanyThrowsNotFound() {
		given(companyRepository.findById(99L)).willReturn(Optional.empty());

		assertThatExceptionOfType(ResourceNotFoundException.class)
				.isThrownBy(() -> service.create(new NewJobApplication(99L, null, "Java Developer", null)))
				.withMessage("Company 99 not found");
		verify(jobApplicationRepository, never()).save(any());
	}

	@Test
	void getUnknownIdThrowsNotFound() {
		given(jobApplicationRepository.findById(99L)).willReturn(Optional.empty());

		assertThatExceptionOfType(ResourceNotFoundException.class)
				.isThrownBy(() -> service.get(99L));
	}

	/** An application with id 5 that has gone through the given status changes. */
	private JobApplication application(Status... path) {
		JobApplication application = withId(new JobApplication(acme, "Java Developer", null), 5L);
		for (Status status : path) {
			application.changeStatus(status);
		}
		return application;
	}

	// ids are generated by the database; the mocks simulate that
	private static <T> T withId(T entity, Long id) {
		ReflectionTestUtils.setField(entity, "id", id);
		return entity;
	}

}
